version: '3.7'

services:
  worker-ai-avatar-mv:
    image: ai-avatar-mv
    container_name: worker-ai-avatar-mv
    volumes:
      - .:/app
      - ./pretrained_models:/app/pretrained_models
      - app-public-volume-v2:/app/static/public/ai_cover_gen
    command: bash -c "celery -A ai_celery.router worker -Q ai_avatar_mv --loglevel=info --pool=eventlet --concurrency=1 -E --logfile=logs/celery.log --hostname=celery@ai_avatar_mv && tail -f /dev/null" &
    restart: always
    networks:
      - aiservice-net-dev-v2
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

volumes:
  "app-public-volume-v2":
    external: true

networks:
  aiservice-net-dev-v2:
    external: true